title: Abhijit’s ML Journey
description: My journey learning Machine Learning, Deep Learning & AI — with notes, references, and projects.
theme: jekyll-theme-cayman
google_analytics:
markdown: kramdown
